// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

package wsPool

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMsg struct {
	Cmd                  int32    `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FromClientId         string   `protobuf:"bytes,3,opt,name=fromClientId,proto3" json:"fromClientId,omitempty"`
	ToClientId           string   `protobuf:"bytes,4,opt,name=toClientId,proto3" json:"toClientId,omitempty"`
	CmdData              []byte   `protobuf:"bytes,5,opt,name=cmdData,proto3" json:"cmdData,omitempty"`
	MsgId                string   `protobuf:"bytes,6,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,8,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Cmdkey               string   `protobuf:"bytes,9,opt,name=cmdkey,proto3" json:"cmdkey,omitempty"`
	Priority             int32    `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	LocalId              int32    `protobuf:"varint,11,opt,name=localId,proto3" json:"localId,omitempty"`
	PageKey              string   `protobuf:"bytes,12,opt,name=pageKey,proto3" json:"pageKey,omitempty"`
	Channel              []string `protobuf:"bytes,13,rep,name=channel,proto3" json:"channel,omitempty"`
	PageId               string   `protobuf:"bytes,14,opt,name=pageId,proto3" json:"pageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsg) Reset()         { *m = SendMsg{} }
func (m *SendMsg) String() string { return proto.CompactTextString(m) }
func (*SendMsg) ProtoMessage()    {}
func (*SendMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{0}
}

func (m *SendMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsg.Unmarshal(m, b)
}
func (m *SendMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsg.Marshal(b, m, deterministic)
}
func (m *SendMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsg.Merge(m, src)
}
func (m *SendMsg) XXX_Size() int {
	return xxx_messageInfo_SendMsg.Size(m)
}
func (m *SendMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsg proto.InternalMessageInfo

func (m *SendMsg) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *SendMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SendMsg) GetFromClientId() string {
	if m != nil {
		return m.FromClientId
	}
	return ""
}

func (m *SendMsg) GetToClientId() string {
	if m != nil {
		return m.ToClientId
	}
	return ""
}

func (m *SendMsg) GetCmdData() []byte {
	if m != nil {
		return m.CmdData
	}
	return nil
}

func (m *SendMsg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *SendMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SendMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SendMsg) GetCmdkey() string {
	if m != nil {
		return m.Cmdkey
	}
	return ""
}

func (m *SendMsg) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *SendMsg) GetLocalId() int32 {
	if m != nil {
		return m.LocalId
	}
	return 0
}

func (m *SendMsg) GetPageKey() string {
	if m != nil {
		return m.PageKey
	}
	return ""
}

func (m *SendMsg) GetChannel() []string {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *SendMsg) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func init() {
	proto.RegisterType((*SendMsg)(nil), "wsPool.SendMsg")
}

func init() {
	proto.RegisterFile("cmd.proto", fileDescriptor_7520252fb01eaf30)
}

var fileDescriptor_7520252fb01eaf30 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xe9, 0xd6, 0x6d, 0xb7, 0x63, 0x15, 0x09, 0x22, 0x83, 0x88, 0x84, 0x3d, 0xf5, 0xe4,
	0xc5, 0x47, 0xd0, 0x4b, 0x91, 0x05, 0xa9, 0x4f, 0x10, 0x93, 0x58, 0x8b, 0x49, 0x53, 0x9a, 0x88,
	0xf4, 0xb1, 0x7d, 0x03, 0xc9, 0xb4, 0x5d, 0xf5, 0x36, 0xdf, 0xff, 0xff, 0x19, 0xfe, 0x30, 0x50,
	0x48, 0xab, 0xee, 0x86, 0xd1, 0x05, 0xc7, 0xb2, 0x2f, 0xff, 0xec, 0x9c, 0xd9, 0x7f, 0x6f, 0x20,
	0x7f, 0xd1, 0xbd, 0x3a, 0xf8, 0x96, 0x5d, 0x40, 0x2a, 0xad, 0xc2, 0x84, 0x27, 0xd5, 0xb6, 0x89,
	0x23, 0xbb, 0x81, 0x22, 0x74, 0x56, 0xfb, 0x20, 0xec, 0x80, 0x1b, 0x9e, 0x54, 0x69, 0xf3, 0x2b,
	0xb0, 0x3d, 0x94, 0x6f, 0xa3, 0xb3, 0x0f, 0xa6, 0xd3, 0x7d, 0xa8, 0x15, 0xa6, 0x3c, 0xa9, 0x8a,
	0xe6, 0x9f, 0xc6, 0x6e, 0x01, 0x82, 0x3b, 0x26, 0x4e, 0x28, 0xf1, 0x47, 0x61, 0x08, 0xb9, 0xb4,
	0xea, 0x51, 0x04, 0x81, 0x5b, 0x9e, 0x54, 0x65, 0xb3, 0x22, 0xbb, 0x84, 0xad, 0xf5, 0x6d, 0xad,
	0x30, 0xa3, 0x47, 0x33, 0xb0, 0x2b, 0xc8, 0x7c, 0x10, 0xe1, 0xd3, 0x63, 0x4e, 0x35, 0x17, 0x8a,
	0xdd, 0x0f, 0xbe, 0xc5, 0x1d, 0x65, 0xe3, 0x18, 0x93, 0xd2, 0xaa, 0x0f, 0x3d, 0x61, 0x41, 0xe2,
	0x42, 0xec, 0x1a, 0x76, 0xc3, 0xd8, 0xb9, 0xb1, 0x0b, 0x13, 0x02, 0xed, 0x38, 0x72, 0x6c, 0x63,
	0x9c, 0x14, 0xa6, 0x56, 0x78, 0x4a, 0xd6, 0x8a, 0xd1, 0x19, 0x44, 0xab, 0x9f, 0xf4, 0x84, 0x25,
	0xad, 0x5b, 0x91, 0x7e, 0xf0, 0x2e, 0xfa, 0x5e, 0x1b, 0x3c, 0xe3, 0x69, 0x74, 0x16, 0x8c, 0x0d,
	0x62, 0xa8, 0x56, 0x78, 0x3e, 0x37, 0x98, 0xe9, 0x35, 0xa3, 0x13, 0xdc, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x8b, 0xbd, 0xf9, 0x75, 0x8f, 0x01, 0x00, 0x00,
}
