// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: sendMsg.proto

package wsPool

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SendMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd          int32    `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Timestamp    int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`      //消息发送时间
	FromClientId string   `protobuf:"bytes,3,opt,name=fromClientId,proto3" json:"fromClientId,omitempty"` //指令消息的来源。发送者的连接ID
	ToClientId   string   `protobuf:"bytes,4,opt,name=toClientId,proto3" json:"toClientId,omitempty"`     //指令消息的接收者。发送给对应的客户端连接ID
	CmdData      []byte   `protobuf:"bytes,5,opt,name=cmdData,proto3" json:"cmdData,omitempty"`           //对应指令的CmdData1的protobuf的message
	Status       int32    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`            //消息发送响应状态
	Priority     int32    `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`        //用于处理指令队列的优先级的权重值
	LocalId      string   `protobuf:"bytes,8,opt,name=localId,proto3" json:"localId,omitempty"`           //客户端标识消息的id，主要区分相同cmd的不同消息，方便收到回复分发处理等效果,考虑长度问题定义成string
	ServerId     string   `protobuf:"bytes,9,opt,name=serverId,proto3" json:"serverId,omitempty"`         //服务端发送消息的ID,主要区分相同cmd的不同消息，方便服务端收到回复分发处理等效果,考虑长度问题定义成string
	Channel      []string `protobuf:"bytes,10,rep,name=channel,proto3" json:"channel,omitempty"`          //指定需要广播的频道，可以指定一个或多个频道
	Msg          string   `protobuf:"bytes,11,opt,name=msg,proto3" json:"msg,omitempty"`                  //一般用于json数据传递，或消息发送响应内容
	Desc         string   `protobuf:"bytes,12,opt,name=Desc,proto3" json:"Desc,omitempty"`                //消息介绍内容，或其它数据
}

func (x *SendMsg) Reset() {
	*x = SendMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsg) ProtoMessage() {}

func (x *SendMsg) ProtoReflect() protoreflect.Message {
	mi := &file_sendMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsg.ProtoReflect.Descriptor instead.
func (*SendMsg) Descriptor() ([]byte, []int) {
	return file_sendMsg_proto_rawDescGZIP(), []int{0}
}

func (x *SendMsg) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *SendMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendMsg) GetFromClientId() string {
	if x != nil {
		return x.FromClientId
	}
	return ""
}

func (x *SendMsg) GetToClientId() string {
	if x != nil {
		return x.ToClientId
	}
	return ""
}

func (x *SendMsg) GetCmdData() []byte {
	if x != nil {
		return x.CmdData
	}
	return nil
}

func (x *SendMsg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SendMsg) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SendMsg) GetLocalId() string {
	if x != nil {
		return x.LocalId
	}
	return ""
}

func (x *SendMsg) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SendMsg) GetChannel() []string {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *SendMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendMsg) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_sendMsg_proto protoreflect.FileDescriptor

var file_sendMsg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x77, 0x73, 0x50, 0x6f, 0x6f, 0x6c, 0x22, 0xc1, 0x02, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6d, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6d, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sendMsg_proto_rawDescOnce sync.Once
	file_sendMsg_proto_rawDescData = file_sendMsg_proto_rawDesc
)

func file_sendMsg_proto_rawDescGZIP() []byte {
	file_sendMsg_proto_rawDescOnce.Do(func() {
		file_sendMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_sendMsg_proto_rawDescData)
	})
	return file_sendMsg_proto_rawDescData
}

var file_sendMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sendMsg_proto_goTypes = []interface{}{
	(*SendMsg)(nil), // 0: wsPool.SendMsg
}
var file_sendMsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sendMsg_proto_init() }
func file_sendMsg_proto_init() {
	if File_sendMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sendMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sendMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sendMsg_proto_goTypes,
		DependencyIndexes: file_sendMsg_proto_depIdxs,
		MessageInfos:      file_sendMsg_proto_msgTypes,
	}.Build()
	File_sendMsg_proto = out.File
	file_sendMsg_proto_rawDesc = nil
	file_sendMsg_proto_goTypes = nil
	file_sendMsg_proto_depIdxs = nil
}
